# Generated by Django 5.1.7 on 2025-04-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
